// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ETLVentas.Data.Models;

[Index("CityName", "CountryId", Name = "UQ_Cities_CityName_CountryID", IsUnique = true)]
public partial class City
{
    [Key]
    [Column("CityID")]
    public int CityId { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string CityName { get; set; }

    [Column("CountryID")]
    public int CountryId { get; set; }
}