// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ETLVentas.Data.Models;

[Index("CountryName", Name = "UQ__Countrie__E056F201E24719DD", IsUnique = true)]
public partial class Country
{
    [Key]
    [Column("CountryID")]
    public int CountryId { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string CountryName { get; set; }
}