// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ETLVentas.Data.Models;

public partial class HistoricalOrder
{
    [Key]
    [Column("OrderID")]
    public int OrderId { get; set; }

    [Column("CustomerID")]
    public int CustomerId { get; set; }

    public DateOnly OrderDate { get; set; }

    [Required]
    [StringLength(60)]
    [Unicode(false)]
    public string Status { get; set; }
}