// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ETLVentas.Data.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ETLVentas.Data.Context
{
    public partial interface IAnalisisDeVentasContextProcedures
    {
        Task<int> sp_InsertCategoryAsync(string categoryName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_InsertCityAsync(string cityName, int? countryID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_InsertCountryAsync(string countryName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_InsertCustomerAsync(int? customerID, string firstName, string lastName, string email, string phone, int? cityID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_InsertOrderAsync(int? orderID, int? customerID, string status, DateOnly? orderDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_InsertOrderDetailAsync(int? orderID, int? productID, int? quantity, decimal? totalPrice, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_InsertProductAsync(int? productID, string productName, int? categoryID, decimal? price, int? stock, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
